services:
  app:
    build: .
    env_file: .env.development
    depends_on:
      - db
    volumes:
      - shared-volume1:/db
    ports:
      - "3000:3000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - shared-volume1:/db

volumes:
  shared-volume1:
