services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - shared-volume:/db
    ports:
      - "3000:3000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - shared-volume:/db

volumes:
  shared-volume:
