services:
  app:
    build: .
    env_file: .env.development
    depends_on:
      - db
    volumes:
      - shared-volume1:/db
    ports:
      - "3000:3000"

  db:
    build: db/.
    env_file: .env.development
    restart: always
    ports:
      - "3307:3307"
    volumes:
      - shared-volume1:/db

volumes:
  shared-volume1:
