services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - shared-volume:/db

  app:
    build: .
    depends_on:
      - db
    volumes:
      - shared-volume:/db

volumes:
  shared-volume:
